import { StyleSheet } from "react-native";
import { LIGHT_COLOR, DARK_COLOR, PRIMARY_COLOR } from "@utils/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: LIGHT_COLOR,
  },
  content: {
    alignItems: "center",
    paddingHorizontal: "5%",
    paddingVertical: 40,
  },
  headerText: {
    color: DARK_COLOR,
    fontFamily: "Montserrat SemiBold 600",
    fontSize: 30,
    width: "100%",
    textAlign: "left",
    marginBottom: 30,
  },
  descriptionText: {
    color: DARK_COLOR,
    fontFamily: "Montserrat Regular 400",
    fontSize: 18,
    width: "100%",
    textAlign: "left",
    marginBottom: 80,
  },
  waterfallContent: {
    width: "100%",
    height: 165,
    paddingBottom: 15,
    position: "relative",
  },
  horizontalLine: {
    position: "absolute",
    bottom: 50,
    height: 50,
    width: "100%",
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 10,
  },
  lineContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "space-around",
    flexDirection: "row",
    gap: 150,
    paddingHorizontal: 100,
  },
  line: {
    height: 150,
    width: 1,
    backgroundColor: PRIMARY_COLOR,
  },
  circleContainer: {
    justifyContent: "space-around",
    flexDirection: "row",
    alignItems: "center",
    height: 150,
    gap: 150,
    paddingHorizontal: 100,
  },
  circleWrapper: {
    alignItems: "center",
    position: "relative",
  },
  circleTitle: {
    position: "absolute",
    bottom: "31%",
    width: 180,
    left: "55%",
    fontFamily: "Montserrat SemiBold 600",
    fontSize: 18,
    textAlign: "left",
    color: DARK_COLOR,
  },
  circle: {
    backgroundColor: LIGHT_COLOR,
    borderRadius: 100,
    height: 43,
    width: 42,
    justifyContent: "center",
    alignItems: "center",
  },
  circleNumber: {
    fontFamily: "Montserrat Medium 500",
    fontSize: 30,
    color: DARK_COLOR,
    textAlign: "center",
    lineHeight: 37,
  },
  circleText: {
    position: "absolute",
    top: "31%",
    left: "55%",
    width: 180,
    fontFamily: "Montserrat Regular 400",
    fontSize: 14,
    color: DARK_COLOR,
    textAlign: "left",
  },
});
